name: Test, Build and Conditional Release (.NET Framework 4.8)

on:
  push:
    branches:
      - '**'   # Build on push to any branch
    tags:
      - 'v*'   # Also triggers on version tags

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run Unit Tests (Linux)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Sesuaikan dengan target test kamu

    - name: Restore NuGet packages
      run: dotnet restore DbServiceTests/DbServiceTests.csproj

    - name: Build test project
      run: dotnet build DbServiceTests/DbServiceTests.csproj --configuration Release

    - name: Run tests
      run: dotnet test DbServiceTests/DbServiceTests.csproj --no-build --configuration Release --verbosity normal

  build:
    runs-on: windows-latest
    needs: test
    name: Build WinForms App

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore RisetGithubActionOnWindowsForm.sln

    - name: Build solution
      run: msbuild RisetGithubActionOnWindowsForm.sln /p:Configuration=Release

    - name: Zip all Release outputs
      run: |
        Compress-Archive -Path (Get-ChildItem -Path . -Recurse -Include *.exe,*.dll | ForEach-Object { $_.FullName }) -DestinationPath WinFormsApp.zip
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinFormsApp
        path: WinFormsApp.zip

  release:
    name: Release if Tag on Main
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required to check commit history
        
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: WinFormsApp

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: WinFormsApp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
